#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <input mp4>"
  exit 1
fi
FILENAME=$(basename -- $1)
DIRNAME=$(dirname -- $1)
echo $FILENAME
echo $DIRNAME
ffmpeg -i $DIRNAME/$FILENAME -pix_fmt yuv420p $DIRNAME/twitter_$FILENAME
